import '@fontsource-variable/outfit';

import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
   title: 'To do App',
   description: 'Generated by create next app',
};

import { Toaster } from 'sonner';

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className="antialiased bg-[#F8FAFC]">
            <Toaster position="top-center" richColors={true} />
            {children}
         </body>
      </html>
   );
}
